# cloudbuild.yaml - Google Cloud Build Configuration
steps:
  # Install dependencies for backend
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: 'backend'

  # Install dependencies for frontend
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'

  # Build frontend
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'
    env:
      - 'VITE_API_URL=${_API_URL}'

  # Build and push backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/elderly-fitness-backend:$BUILD_ID'
      - '-f'
      - 'backend/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/elderly-fitness-backend:$BUILD_ID']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'elderly-fitness-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/elderly-fitness-backend:$BUILD_ID'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,DB_HOST=${_DB_HOST},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},DB_NAME=${_DB_NAME},JWT_SECRET=${_JWT_SECRET}'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'

substitutions:
  _API_URL: 'https://elderly-fitness-api-xxxxx-as.a.run.app'
  _DB_HOST: '35.194.136.118'
  _DB_USER: 'postgres'
  _DB_PASSWORD: 'WiSiNG1234'
  _DB_NAME: 'fitness-tracker-ai'
  _JWT_SECRET: 'your-jwt-secret-key'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'



# app.yaml - App Engine Configuration (Alternative to Cloud Run)
runtime: nodejs18

env_variables:
  NODE_ENV: production
  DB_HOST: "35.194.136.118"
  DB_USER: "postgres"
  DB_PASSWORD: "WiSiNG1234"
  DB_NAME: "fitness-tracker-ai"
  JWT_SECRET: "your-jwt-secret"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /.*
    static_files: public/\1
    upload: public/.*
    secure: always